### PR TITLE
Point cowsay submodule to the official repo

### PR DESCRIPTION
**Pull request by sitiom**
Bumps cowsay to 3.04 as well

### CODE REVIEW

**Comment by sitiom** [comment]
@iwataka Any plans on merging this?

**Comment by iwataka** [comment]
@sitiom 
Sorry for the long delay.
I couldn't find an evidence why [that repository](https://github.com/tnalpgge/rank-amateur-cowsay) is the official one.
Could you explain it to me ?

**Comment by sitiom** [comment]
> @sitiom Sorry for the long delay. I couldn't find an evidence why [that repository](https://github.com/tnalpgge/rank-amateur-cowsay) is the official one. Could you explain it to me ?



@iwataka [tnalpgge](https://github.com/tnalpgge) is Tony Monroe's [GitHub account](https://tnalpgge.github.io). The [Wikipedia](https://en.wikipedia.org/wiki/Cowsay) article also points to that GitHub repository.

**Comment by iwataka** [comment]
@sitiom 
OK. Would you mind updating README also ?

**Comment by sitiom** [comment]
Done.

**Comment by iwataka** [comment]
@sitiom 
Thank you for your work. I merged.

**Pull request merged**
